export const levels = [
  {
    id: "starter-arcade",
    title: "Starter Arcade",
    theme: "Browser games and puzzle words",
    difficulty: "Easy",
    accent: "#35c7ff",
    glow: "#ffe66d",
    size: 12,
    words: [
      "CROSSWORD",
      "PUZZLE",
      "SEARCH",
      "WORDS",
      "LEVEL",
      "HINT",
      "SWIPE",
      "BOARD",
    ],
    placements: [
      { word: "CROSSWORD", row: 7, col: 1, dr: 0, dc: 1 },
      { word: "PUZZLE", row: 5, col: 6, dr: -1, dc: 1 },
      { word: "SEARCH", row: 8, col: 0, dr: 0, dc: 1 },
      { word: "WORDS", row: 2, col: 11, dr: 1, dc: 0 },
      { word: "LEVEL", row: 5, col: 7, dr: -1, dc: -1 },
      { word: "HINT", row: 9, col: 0, dr: 0, dc: 1 },
      { word: "SWIPE", row: 6, col: 4, dr: 0, dc: 1 },
      { word: "BOARD", row: 3, col: 10, dr: 1, dc: 0 },
    ],
  },
  {
    id: "solar-run",
    title: "Solar Run",
    theme: "Sky, space, and motion",
    difficulty: "Medium",
    accent: "#ff8a3d",
    glow: "#78f0c4",
    size: 13,
    words: [
      "ORBIT",
      "COMET",
      "GALAXY",
      "RADIANT",
      "VECTOR",
      "ROCKET",
      "LUNAR",
      "NOVA",
      "PLASMA",
      "SUNRISE",
    ],
    placements: [
      { word: "ORBIT", row: 8, col: 0, dr: 1, dc: 0 },
      { word: "COMET", row: 6, col: 4, dr: 0, dc: 1 },
      { word: "GALAXY", row: 7, col: 1, dr: 1, dc: 1 },
      { word: "RADIANT", row: 5, col: 5, dr: 0, dc: 1 },
      { word: "VECTOR", row: 12, col: 12, dr: 0, dc: -1 },
      { word: "ROCKET", row: 5, col: 5, dr: 1, dc: 0 },
      { word: "LUNAR", row: 7, col: 3, dr: -1, dc: 0 },
      { word: "NOVA", row: 2, col: 12, dr: 0, dc: -1 },
      { word: "PLASMA", row: 3, col: 9, dr: 1, dc: 0 },
      { word: "SUNRISE", row: 7, col: 2, dr: -1, dc: 1 },
    ],
  },
  {
    id: "night-market",
    title: "Night Market",
    theme: "Color, sound, and city energy",
    difficulty: "Hard",
    accent: "#a78bfa",
    glow: "#fb7185",
    size: 14,
    words: [
      "NEON",
      "MOSAIC",
      "RHYTHM",
      "LANTERN",
      "ARCADE",
      "VENDOR",
      "SIGNAL",
      "PLAZA",
      "STREET",
      "BANNER",
      "CHROME",
      "TICKETS",
    ],
    placements: [
      { word: "NEON", row: 3, col: 10, dr: 1, dc: -1 },
      { word: "MOSAIC", row: 4, col: 7, dr: 1, dc: -1 },
      { word: "RHYTHM", row: 13, col: 10, dr: 0, dc: -1 },
      { word: "LANTERN", row: 2, col: 11, dr: 0, dc: -1 },
      { word: "ARCADE", row: 7, col: 1, dr: 1, dc: 1 },
      { word: "VENDOR", row: 3, col: 9, dr: 1, dc: -1 },
      { word: "SIGNAL", row: 12, col: 12, dr: 0, dc: -1 },
      { word: "PLAZA", row: 12, col: 13, dr: -1, dc: -1 },
      { word: "STREET", row: 1, col: 13, dr: 1, dc: -1 },
      { word: "BANNER", row: 6, col: 3, dr: 1, dc: 1 },
      { word: "CHROME", row: 8, col: 0, dr: 1, dc: 0 },
      { word: "TICKETS", row: 6, col: 4, dr: -1, dc: 0 },
    ],
  },
];

export const fillerAlphabet = "ETAOINSHRDLCUMWFGYPBVKXJQZ";
